spring:
  application:
    name: buy-zone-api
    version: 1.0.0 # Versao da API
  profiles:
    active: test
  output:
    ansi:
      enabled: ALWAYS

springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
  api-docs:
    path: /buy-zone-api/v3/api-docs

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: ${SERVER_PORT:8090}

info:
  app:
    name: ${spring.application.name}
    api-version: ${spring.application.version}
    java-version: ${java.version}
    spring-boot-version: ${spring-boot.version}
