output:
  ansi:
    enabled: ALWAYS
# ==================================
# Configuração Application - Production
# ==================================
spring:
  cloud:
    config:
      enabled: false
  # jpa:
  #   generate-ddl: true
  #   properties:
  #     jakarta.persistence.schema-generation.scripts.action: create
  #     jakarta.persistence.schema-generation.scripts.create-target: ${JPA_SCRIPTS_CREATE_TARGET}
  #     jakarta.persistence.schema-generation.create-source: ${JPA_CREATE_SOURCE}
  #     hibernate.dialect: ${HIBERNATE_DIALECT}
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}

server:
  port: ${SERVER_PORT}

# ==================================
# Configuração actuator e observabilidade
# ==================================
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_INCLUDE}
    access:
      default: ${MANAGEMENT_ACCESS_DEFAULT}
  endpoint:
    refresh:
      enabled: ${MANAGEMENT_ENDPOINT_REFRESH_ENABLED}
    health:
      enabled: ${MANAGEMENT_ENDPOINT_HEALTH_ENABLED}
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}
    info:
      enabled: ${MANAGEMENT_ENDPOINT_INFO_ENABLED}
    metrics:
      enabled: ${MANAGEMENT_ENDPOINT_METRICS_ENABLED}
    prometheus:
      enabled: ${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED}

# ==================================
# Configuração de logging
# ==================================
logging:
  pattern:
    console: "${LOGGING_PATTERN_CONSOLE}"
  level:
    root: ${LOGGING_LEVEL_ROOT}

springdoc:
  swagger-ui:
    operationsSorter: ${SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER}
    path: ${SPRINGDOC_SWAGGER_UI_PATH}
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH}

pagseguro:
  authorization-token: ${PAGSEGURO_AUTH_TOKEN}

# ==================================
# Configuração Security application
# ==================================
security:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  jwt:
    duration: ${JWT_DURATION}
