spring:
  application:
    name: buy-zone-api
    version: 1.0.0
  profiles:
    active: dev
info:
  app:
    name: ${spring.application.name}
    api-version: ${spring.application.version}
    java-version: ${java.version}
    spring-boot-version: ${spring-boot.version}