networks:
  buy_zone_app_network:
    driver: bridge

volumes:
  grafana-storage:

services:
  # ====================================================================================================================
  # POSTGRES BUY ZONE ECOMMERCE DB
  # ====================================================================================================================
  postgres-buy-zone:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres-buy-zone-db
    environment:
      POSTGRES_DB: buy-zone-db
      POSTGRES_PASSWORD: 1234567
      TZ: "America/Sao_Paulo"
    ports:
      - 5439:5432
    volumes:
      - ./data/buy-zone-db/data:/etc/postgresql/data
    networks:
      - buy_zone_app_network
    profiles:
      - buy-zone-database

  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-buy-zone:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    container_name: guidb-pgadmin-4-buy-zone
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5053:80
    volumes:
      - ./data/pgadmin:/etc/pgadmin
    networks:
      - buy_zone_app_network
    profiles:
      - pgadmin-guid

  # ====================================================================================================================
  # PROMETHEUS
  # ====================================================================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-buy-zone-api
    networks:
      - buy_zone_app_network
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - ./dados:/prometheus
    ports:
      - "9098:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    user: root
    restart: unless-stopped
    profiles:
      - observability

  # ====================================================================================================================
  # GRAFANA
  # ====================================================================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-buy-zone-api
    networks:
      - buy_zone_app_network
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:z
    restart: unless-stopped
    depends_on:
      - prometheus
    profiles:
      - observability
  # ====================================================================================================================
  # LOKI (Logs)
  # ====================================================================================================================
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    volumes:
      - ./observability/loki/data:/loki
      - ./observability/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./observability/loki/wal:/wal
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    profiles:
      - observability
    networks:
      - buy_zone_app_network
    restart: unless-stopped
